### ISSUE TITLE
Create labels for GitLab groups

### ISSUE THREAD

**Issue by saily** [dalwar23/labelx#7]
* labelx version: 2.1.1
* Python version: 3.8.10
* Operating System: OSX

### Feature request

GitLab supports group and subgroup labels, it would be nice to extend label sync on group level, so `labelx` could be launched by running: 
```
labelx create-labels \
    -g 34 \         # example group id of the to be synced/updated group
    -f labels.yaml  # decouple the shipped file from one we could inject here. 
```

**Comment by saily** [comment]
@dalwar23 are you still maintaining this project?

**Comment by dalwar23** [comment]
I was busy with other projects but injecting labels from a file w/ `-f lables.yaml`  is planned. I plan to work on it soon.

**Comment by dalwar23** [comment]
@saily `v2.3.0` is out. [See Documentation](https://labelx.readthedocs.io/en/latest/). This should address the issues/enhancement you mentioned. If you see a bug 🐛 , plese open an issue. cheers! 🧀
